branches:
  only:
  - master
language: python
python:
- '3.4'
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- npm install -g jshint
addons:
  postgresql: '9.6'
before_script:
- mv configs/config.py.travis occrp/app_config.py
script: 
- pytest tests
- jshint occrp/static/js/custom.js
deploy:
  provider: codedeploy
  access_key_id: AKIAJNYGDLOJKHOUWCAA
  secret_access_key:
    secure: hpqlVMhE7Gth6vPCfAAOpwluZ1auk+fCdnNYs97cCNXETKCLiJf5wLbrWJjKhN4rMv04QB5FuPR2AXM7idMS7UFOeG+bzyXTpg5j0PHknOoTLZ2niXVuExqcfq4unaDk8ROftoDCjywDIIuAIUFsoIQBeEd99EsaYoraLBG2uxZx3rPvd1ingMCsO3SmJvBu9VzGj2cSvo2rUWCskQtFkTIjko6RcHPAPXrZUHMugdEs6KpWT5kXb4n5GOvRGYJecqU7Na+0cpbjdFU5p7rNMOY8jj6fLp/kz8VmVjsYjbf3l3MWjTZ0sYBHSyrnGTNi/baqlMbAAtSqsu7hEgA+Vjbsy5e0pPjkXzWsEDBpeC1YTSMThRSpPhidYGbAb7jODjDOHqUmYS+Ayc8TLPOybd/gm6iAR9O1lWTuB+m7qTPDZ0BkeV75TrrJlUewjGpylb/hTWnsFdvmmrtFsbhtY+Xo1ewE9nmXBp+q8YjH86idFPS0mhL6uhGzs/C0IHWhSvFSFAnp1TWlHFDqx1JNIEboGlbKaw402VWEV4lLLd6iPZD7gq4HbFCfErzvcZp1R+o8inn3Al1MnWXNd2aMXgjmqJFdYdFgz11YxI/gl1hNc4OEOXyJTsgYdwBGstTw2aSOR0y4GY8BTebd8rbAmTwLWb7mAbBVvPRmFwzRM5s=
  application: occrp
  deployment_group: staging
  on:
    branch: master
