"""Fix relation

Revision ID: 550127b0c073
Revises: 5f6302b63190
Create Date: 2017-09-15 15:49:31.303056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550127b0c073'
down_revision = '5f6302b63190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
