"""Remove event title and create location model

Revision ID: 5f6302b63190
Revises: b20c5f6f1459
Create Date: 2017-09-15 15:42:27.841136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6302b63190'
down_revision = 'b20c5f6f1459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.add_column('event', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_constraint('event_title_key', 'event', type_='unique')
    op.create_foreign_key(None, 'event', 'location', ['location_id'], ['id'])
    op.drop_column('event', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_unique_constraint('event_title_key', 'event', ['title'])
    op.drop_column('event', 'location_id')
    op.drop_table('location')
    # ### end Alembic commands ###
