"""Add date accuracy

Revision ID: b20c5f6f1459
Revises: 21c9076fc052
Create Date: 2017-07-10 10:48:19.266852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20c5f6f1459'
down_revision = '21c9076fc052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_date_accuracy', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('start_date_accuracy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'start_date_accuracy')
    op.drop_column('event', 'end_date_accuracy')
    # ### end Alembic commands ###
