"""Add db to event_type and location

Revision ID: b75858eb342f
Revises: 17fd243e4dc4
Create Date: 2017-09-19 11:55:40.421098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75858eb342f'
down_revision = '17fd243e4dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
